name: FlaskSimpleAuth documentation publication on GitHub

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install sphinx sphinx-autoapi sphinx-rtd-theme myst_parser
          python -m pip install .
      - name: Generate documentation
        run: make -C docs html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
